### ISSUE TITLE
https://www.virustotal.com/gui/file/883eebcae0cc81ff05f20d636cb38ac3a993bed92bde2df16606d8230dbbd4d9/detection

### ISSUE THREAD

**Issue by ALEHACKsp** [csgopravo/gamesense.plus#1]
https://www.virustotal.com/gui/file/883eebcae0cc81ff05f20d636cb38ac3a993bed92bde2df16606d8230dbbd4d9/detection

**Comment by Mikquaj** [comment]
ok and?

**Comment by ALEHACKsp** [comment]
It doesn't make sense for you to be posting shit on github, even more a fake DLL saying it's GAMESENSE LOL, Stop being a sucker!

**Comment by Mikquaj** [comment]
![image](https://user-images.githubusercontent.com/81552040/155549321-cb1b0380-ee48-4ea7-9d34-61388172133e.png)
iq?
